#define WM_SOCK  WM_USER+5
#define WM_MSG	 WM_USER+6
#define WM_ADD	WM_MSG
#define WM_CHATMSG	WM_MSG
#define	WM_RESTARTTHREAD WM_USER+7
#define NETMSG_CHAT 1
#define NETMSG_CMD  2
#define NETMSG_KEYBOARD 3
#define NETMSG_MOUSE    4
#define NETMSG_MONINITOK	5
#define NETMSG_SCRINFO	6
#define NETMSG_SETMONRECT	7
#define NETMSG_DOWNFILE	8
#define NETMSG_UPFILE	9
#define NETMSG_GETDRIVERS	10
#define NETMSG_INITINFO		11
#define NETMSG_GETFILELIST	12
#define NETMSG_FILELIST		13
#define NETMSG_FLODER	14
#define NETMSG_CMDEND	15
#define IDM_DOWNFILE	16
#define IDM_UPFILE		17
#define IDM_DELFILE		18
#define IDM_RENAMEFILE	19
#define	IDM_EXECUTE		20
#define IDM_NEWFLODER	21
#define NETMSG_GETPORT	22
#define NETMSG_PORT		23
#define NETMSG_GETSCRINFO 24
#define FT_DATALEN		50
#define FT_LASTOK		51//最后一次确认ok
#define FT_LASTFAIL		56//最后一次失败
#define FT_SIZE			52
#define FT_GETSIZE		53
#define FT_FILEEND		54//文件传输完毕
#define FT_FILEBREAK	55//文件传输中止
#define NETMSG_DELFILE	57
#define NETMSG_DELFLODER	58
#define IDM_STARTMON                    40002
#define IDM_ENDMON                      40003
#define IDM_SHTUDOWN                    40005
#define IDM_CAPSCR                      40006